### ISSUE TITLE
The encryption password is always the root password, the user input is ignored

### ISSUE THREAD

**Issue by aafeijoo-suse** [openSUSE/disk-encryption-tool#6]
While testing the MicroOS image specified in https://bugzilla.suse.com/show_bug.cgi?id=1218068#c23, I set an encryption password different than the root password, but the system was encrypted using the root password anyway.

Maybe the following line is wrong and it should use `$crypt_pw` instead of `$password`?

https://github.com/openSUSE/disk-encryption-tool/blob/6a5fb7feef514da079487c123c015765d202f868/jeos-firstboot-diskencrypt#L62

**Comment by lnussel** [comment]
damn. right

**Comment by lnussel** [comment]
fixed in https://github.com/openSUSE/disk-encryption-tool/commit/d2e7fe6e0781b71a19f35ca4fd27bca559c31fd7m, thanks!

**Comment by aafeijoo-suse** [comment]
yw!
